In [97]:
import pandas as pd
import requests
import os
from calculadora_inflacao import CalculadoraFatorInflacao

# APOGESP
## Cálculo de impacto orçamentário das propostas reajuste salarial para os APPGGS

Esse notebook realiza a estimativa de impacto orçamentário das propostas de reajuste salarial feitas pela APOGESP para a campanha salarial de 2026 na Prefeitura de São Paulo.

São consideradas duas propostas principais:
1. Reajuste inflacionário, que se subdivide em:
    1. Reajuste da tabela original da carreira considerando a inflação acumulada desde as primeiras nomeações (jun/2026)
    2. Reajuste da tabela da carreira considerando a inflação acumulada na gestão Ricardo Nunes e a tabela no momento de início da gestão (jun/2021)
2. Equiparação com a tabela dos AMCI (ou seja, unificação da estrutura remuneratória do quadro QPPGG)


Em ambos os casos, a estimativa segue a seguinte metodologia:

1. Identificação dos APPGGs em exercício (incluso cedidos) segundo os últimos dados disponíveis no portal de dados abertos (dezembro de 2025),
2. Atualização dos dados do item 1 considerando o acréscimo dos 30 APPGGs recém-nomeados no nível 1, criando dados sintéticos (novas linhas na tabela)
3. Cálculo do salário base atual de cada APPGG considerando a tabela atual e o nível em que ele se encontra,
4. Cálculo dos encargos e benefícios que tem como base o salário atual como contribuição previdenciária obrigatória, auxílio transporte, auxílio alimentação etc.
5. Cálculo do salário proposto considerando o nível em que o APPGG se encontra atualmente e a tabela atualizada proposta
6. Cálculo dos encargos citados no item 6,
7. Somatória dos salários e encargos para cada APPGG considerando a tabela atual e a tabela proposta,
8. Cálculo da diferença entre a situação atual e a situação proposta conforme item 7,
9. Somatória da diferença por nível da carreira APPGG (p. ex., para o nível 1 a proposta implica em X mil reais mensais para a Prefeitura para o nível 2, y mil reais etc.)
10. Simulação de progressão da carreira considerando 18 meses para a "subida" de nível e projeção do impacto orçamentário anual até o final da gestão (2028)

O diagrama na imagem abaixo representa as etapas da metodologia.

![Grafo da metodologia](mermaid_graph.svg)

## Dados servidores

Nessa seção pegamos os dados dos servidores ativos mais atualizados (dezembro de 2025) do portal de dados abertos. Em seguida, identificamos os APPGGs e adicionamos dados sintéticos referentes aos APPGGs recém-nomeados.

In [98]:
URL_SERVIDORES = 'https://dados.prefeitura.sp.gov.br/dataset/bf5df0f4-4fb0-4a5e-b013-07d098cc7b1c/resource/459da127-4642-4412-a3f1-762d42a165ff/download/verificado_ativos_03-06-2026_mai-2026.csv'
file_dados = 'servidores_ativos_maio.csv'

In [99]:
def download_dados_servidores(fname:str, url:str=URL_SERVIDORES)->str:

    if not os.path.exists(fname):
        print('Downloading data')
        with requests.get(url) as r:
            r.raise_for_status()
            content = r.content
            with open(fname, 'wb') as f:
                f.write(content)
            
            assert os.path.exists(fname)
            return fname
    return fname

In [100]:
file_dados = download_dados_servidores(file_dados)

In [101]:
df = pd.read_csv(file_dados, encoding='latin1', sep=';')

In [102]:
df.head()

,REGISTRO,VINCULO,NOME,CARGO_BASICO,REF_CARGO_BAS,SEGMENTO,GRUPO,SUBGRUPO,ESCOL_CARGO_BASICO,CARGO_COMISSAO,...,SECRET_SUBPREF,SIGLA,SETOR,DISTRITO,SUBPREFEITURA,ORGAO_EXT,SEXO,ANO_NASCIMENTO,RACA_COR,PCD
0,1145541,16,CLEUZA BORGES PEREIRA SILVA,ASSESSOR IV,CDA-4,NaN,QC,CARGO EM COMISSAO,NAO SE APLICA,NaN,...,SECRETARIA MUNICIPAL DE GESTAO,SEGES,ASSESSORIA JURIDICA,SE,SE,NaN,FEMININO,1949,PARDA,NAO
1,1160206,5,ADILSON DA SILVA,COORDENADOR II,CDA-6,NaN,QC,CARGO EM COMISSAO,SUPERIOR COMPLETO,NaN,...,SUBPREFEITURA SANTO AMARO,SUB-SA,COORDENADORIA DE PLANEJAMENTO E DESENVOLVIMENT...,SANTO AMARO,SANTO AMARO,NaN,MASCULINO,1949,BRANCA,NAO
2,1160478,2,JULIO DE CARVALHO,FISCAL DE POSTURAS MUNICIPAIS NIVEL IV,QFPM15,NaN,QFPM,SUPERIOR,SUPERIOR COMPLETO,NaN,...,SUBPREFEITURA SANTANA/TUCURUVI,SUB-ST,SUPERVISÇO TECNICA DE FISCALIZACAO,TUCURUVI,SANTANA/TUCURUVI,NaN,MASCULINO,1951,BRANCA,NAO
3,1161181,9,NEUSA PEDRAO NASSIR,ASSESSOR V,CDA-5,NaN,QC,CARGO EM COMISSAO,NAO SE APLICA,NaN,...,SECRETARIA DO GOVERNO MUNICIPAL,SGM,ASSESSORIA JURIDICA,SE,SE,NaN,FEMININO,1947,BRANCA,NAO
4,1168185,4,MARIA HELENA DI VERNIERI CUPPARI,ASSISTENTE TECNICO EDUCACIONAL,QPE17A,NaN,QPE L. 14660/07 RGPS,CARGO EM COMISSAO,LICENCIATURA PLENA COMPLETA,NaN,...,SECRETARIA MUNICIPAL DE EDUCACAO,SME,DIRETORIA REGIONAL DE EDUCACAO PIRITUBA/JARAGUA,LAPA,LAPA,NaN,FEMININO,1942,BRANCA,NAO

In [103]:
cargos = df['REF_CARGO_BAS'].unique()

In [104]:
for cargo in cargos:
    if "appgg" in str(cargo).lower():
        print(cargo)

APPGG3
APPGG1
APPGG2
APPGG5
APPGG6
APPGG4

In [105]:
#filtrando para apenas servidores efetivos (ou seja, que possuem cargo base)
df_efetivos = df[df['REF_CARGO_BAS'].notna()]

In [106]:
appggs = df_efetivos[df_efetivos['REF_CARGO_BAS'].str.contains('APPGG')].reset_index(drop=True)

In [107]:
appggs.head()

,REGISTRO,VINCULO,NOME,CARGO_BASICO,REF_CARGO_BAS,SEGMENTO,GRUPO,SUBGRUPO,ESCOL_CARGO_BASICO,CARGO_COMISSAO,...,SECRET_SUBPREF,SIGLA,SETOR,DISTRITO,SUBPREFEITURA,ORGAO_EXT,SEXO,ANO_NASCIMENTO,RACA_COR,PCD
0,6394604,3,CLAUDIO AGUIAR ALMEIDA,ANALISTA POLITICAS PUBLICAS GESTAO GOVERNAMENT...,APPGG3,NaN,QPGG,SUPERIOR,SUPERIOR COMPLETO,NaN,...,SECRETARIA MUNICIPAL DE CULTURA E ECONOMIA CRI...,SMC,SECRETARIA MUNICIPAL DE CULTURA E ECONOMIA CRI...,SE,SE,NaN,MASCULINO,1963,PRETA,NAO
1,7575491,2,MAURICIO DA SILVA CORREIA,ANALISTA POLITICAS PUBLICAS GESTAO GOVERNAMENT...,APPGG1,NaN,QPGG,SUPERIOR,SUPERIOR COMPLETO,NaN,...,SECRETARIA MUNICIPAL DE GESTAO,SEGES,SECRETARIA MUNICIPAL DE GESTAO,SE,SE,PREFEITURA DO MUNICIPIO DE ITAJAI,MASCULINO,1986,BRANCA,NAO
2,7718543,6,MARCIA MIYUKI ISHIKAWA,ANALISTA POLITICAS PUBLICAS GESTAO GOVERNAMENT...,APPGG2,NaN,QPGG,SUPERIOR,SUPERIOR COMPLETO,NaN,...,SECRETARIA MUNICIPAL DE HABITACAO,SEHAB,DEPARTAMENTO DE PLANEJAMENTO HABITACIONAL,SE,SE,NaN,FEMININO,1978,BRANCA,NAO
3,7794720,2,TIAGO ROSA MACHADO,ANALISTA POLITICAS PUBLICAS GESTAO GOVERNAMENT...,APPGG2,NaN,QPGG,SUPERIOR,SUPERIOR COMPLETO,ASSESSOR III,...,SECRETARIA MUNICIPAL DE ESPORTES E LAZER,SEME,SECRETARIA MUNICIPAL DE ESPORTES E LAZER,MOEMA,VILA MARIANA,NaN,MASCULINO,1983,BRANCA,NAO
4,7840501,2,THAIS ROBERTO DA SILVA,ANALISTA POLITICAS PUBLICAS GESTAO GOVERNAMENT...,APPGG5,NaN,QPGG,SUPERIOR,SUPERIOR COMPLETO,NaN,...,SECRETARIA MUNICIPAL DE DIREITOS HUMANOS E CID...,SMDHC,SECRETARIA MUNICIPAL DE DIREITOS HUMANOS E CID...,SE,SE,NaN,FEMININO,1977,PRETA,NAO

In [108]:
appggs = appggs[['REGISTRO', 'NOME', 'REF_CARGO_BAS', 'SIGLA', 'DATA_INICIO_EXERC']]

renomear_cols = {
    'REGISTRO' : 'rf',
    'NOME' : 'nome',
    'REF_CARGO_BAS' : 'cargo_base',
    'SIGLA' : 'secretaria_dez_2025',
    'DATA_INICIO_EXERC' : 'dt_inicio_exercicio'
}

appggs.rename(renomear_cols, axis=1, inplace=True)

In [109]:
appggs['nivel_carreira'] = appggs['cargo_base'].str.extract(r'(\d+)$').astype(int)

In [110]:
appggs.head()

,rf,nome,cargo_base,secretaria_dez_2025,dt_inicio_exercicio,nivel_carreira
0,6394604,CLAUDIO AGUIAR ALMEIDA,APPGG3,SMC,01/10/2021,3
1,7575491,MAURICIO DA SILVA CORREIA,APPGG1,SEGES,03/11/2021,1
2,7718543,MARCIA MIYUKI ISHIKAWA,APPGG2,SEHAB,08/12/2021,2
3,7794720,TIAGO ROSA MACHADO,APPGG2,SEME,05/01/2022,2
4,7840501,THAIS ROBERTO DA SILVA,APPGG5,SMDHC,29/11/2017,5

In [111]:
appggs.shape

(194, 6)

In [112]:
QTD_RECEM_NOMEADOS=0
recem_nomeados = [{
            'rf' : str(i+1).zfill(7),
            'nome' : f'recem_nomeado_{i+1}',
            'cargo_base' : 'APPGG1',
            'secretaria_dez_2025' : 'NA',
            'nivel_carreira' : 1,
            'dt_inicio_exercicio' : '01/03/2026'
            }
            for i in range(QTD_RECEM_NOMEADOS)
            ]

recem_nomeados = pd.DataFrame(recem_nomeados)

In [113]:
recem_nomeados.head()

Empty DataFrame
Columns: []
Index: []

In [114]:
recem_nomeados.shape

(0, 0)

In [115]:
appggs = pd.concat([appggs, recem_nomeados])

In [116]:
appggs.shape

(194, 6)

In [117]:
#vou colocar como datetime porque precisamos calcular com base na data
appggs['dt_inicio_exercicio'] = pd.to_datetime(appggs['dt_inicio_exercicio'], format ="%d/%m/%Y")


#inclusive ja vou definir se a pessoa contribui para o regime proprio (IPREM) ou nao
appggs['contribui_rpps'] = appggs['dt_inicio_exercicio'].dt.year<2018

In [118]:
appggs.head()

,rf,nome,cargo_base,secretaria_dez_2025,dt_inicio_exercicio,nivel_carreira,contribui_rpps
0,6394604,CLAUDIO AGUIAR ALMEIDA,APPGG3,SMC,2021-10-01,3,False
1,7575491,MAURICIO DA SILVA CORREIA,APPGG1,SEGES,2021-11-03,1,False
2,7718543,MARCIA MIYUKI ISHIKAWA,APPGG2,SEHAB,2021-12-08,2,False
3,7794720,TIAGO ROSA MACHADO,APPGG2,SEME,2022-01-05,2,False
4,7840501,THAIS ROBERTO DA SILVA,APPGG5,SMDHC,2017-11-29,5,True

# Situaçao atual

Nessa seção calculamos a situação atual de dispêndio com a carreira de APPGGs por parte da Prefeitura, considerando apenas os vencimentos e os encargos que estão relacionados aos vencimentos, como contribuição previdenciaria.

In [119]:
tabela_atual = {
    1 : 13208.14,
    2 : 14528.96,
    3 : 14892.18,
    4 : 15264.48,
    5 : 15646.09,
    6 : 16037.24,
    7 : 17961.73,
    8 : 18410.77,
    9 : 18871.04,
    10 : 19342.80,
    11 : 19826.39,
    12 : 21869.74,
    13 : 22416.47,
    14 : 22976.89,
    15 : 23551.31
}

In [120]:
def reajuste_maio(tabela:dict[int, float])->dict[int, float]:
    
    fator_reajuste = 0.0351
    return {nivel : round(valor*(1+fator_reajuste), 2) for nivel, valor in tabela.items()}

In [121]:
tabela_atual = reajuste_maio(tabela_atual)
tabela_atual

{1: 13671.75,
 2: 15038.93,
 3: 15414.9,
 4: 15800.26,
 5: 16195.27,
 6: 16600.15,
 7: 18592.19,
 8: 19056.99,
 9: 19533.41,
 10: 20021.73,
 11: 20522.3,
 12: 22637.37,
 13: 23203.29,
 14: 23783.38,
 15: 24377.96}

In [122]:
appggs_atual = appggs.copy(deep=True)

In [123]:
appggs_atual['vencimento'] = appggs_atual['nivel_carreira'].map(tabela_atual)

In [124]:
appggs_atual.head()

,rf,nome,cargo_base,secretaria_dez_2025,dt_inicio_exercicio,nivel_carreira,contribui_rpps,vencimento
0,6394604,CLAUDIO AGUIAR ALMEIDA,APPGG3,SMC,2021-10-01,3,False,15414.90
1,7575491,MAURICIO DA SILVA CORREIA,APPGG1,SEGES,2021-11-03,1,False,13671.75
2,7718543,MARCIA MIYUKI ISHIKAWA,APPGG2,SEHAB,2021-12-08,2,False,15038.93
3,7794720,TIAGO ROSA MACHADO,APPGG2,SEME,2022-01-05,2,False,15038.93
4,7840501,THAIS ROBERTO DA SILVA,APPGG5,SMDHC,2017-11-29,5,True,16195.27

### Terço adicional de férias e décimo terceiro

Nesse caso vamos dividir ambos por 12 são gastos anuais e nossa base é mensal.

In [125]:
def calcular_decimo_terceiro(row):

    return round(row['vencimento']/12, 2)

def calcular_terco_ferias(row):

    return round((row['vencimento']/3)/12, 2)

In [126]:
appggs_atual['decimo_terceiro'] = appggs_atual.apply(calcular_decimo_terceiro, axis=1)

appggs_atual['terco_ferias'] = appggs_atual.apply(calcular_terco_ferias, axis=1)

In [127]:
appggs_atual.head()

,rf,nome,cargo_base,secretaria_dez_2025,dt_inicio_exercicio,nivel_carreira,contribui_rpps,vencimento,decimo_terceiro,terco_ferias
0,6394604,CLAUDIO AGUIAR ALMEIDA,APPGG3,SMC,2021-10-01,3,False,15414.90,1284.58,428.19
1,7575491,MAURICIO DA SILVA CORREIA,APPGG1,SEGES,2021-11-03,1,False,13671.75,1139.31,379.77
2,7718543,MARCIA MIYUKI ISHIKAWA,APPGG2,SEHAB,2021-12-08,2,False,15038.93,1253.24,417.75
3,7794720,TIAGO ROSA MACHADO,APPGG2,SEME,2022-01-05,2,False,15038.93,1253.24,417.75
4,7840501,THAIS ROBERTO DA SILVA,APPGG5,SMDHC,2017-11-29,5,True,16195.27,1349.61,449.87

### Vale alimentação

O vale alimentação só é devido para quem ganha menos de 10 salários minimos. Como com o reajuste essa proporcao pode diminuir, ele deve entrar na conta apesar de ser um valor fixo.

In [128]:
def calcular_va(row):
    SALARIO_MINIMO = 1621
    VALOR_VALE_ALIMENTACAO = 325.25

    if row['vencimento'] <= SALARIO_MINIMO*10:
        return VALOR_VALE_ALIMENTACAO
    return 0

In [129]:
appggs_atual['vale_alimentacao'] = appggs_atual.apply(calcular_va, axis=1)

In [130]:
def vale_refeicao(row):
    #apesar de ser uma constante decidi adicionar para os valores absolutos ficarem mais corretos
    DIAS_MES = 22
    VALOR_DIARIO  = 30.22

    return DIAS_MES*VALOR_DIARIO

In [131]:
appggs_atual['vale_refeicao'] = appggs_atual.apply(vale_refeicao, axis=1)

In [132]:
appggs_atual.sample(3)

,rf,nome,cargo_base,secretaria_dez_2025,dt_inicio_exercicio,nivel_carreira,contribui_rpps,vencimento,decimo_terceiro,terco_ferias,vale_alimentacao,vale_refeicao
21,8235112,TERRA JOHARI POSSA TERRA,APPGG5,SEGES,2016-06-16,5,True,16195.27,1349.61,449.87,325.25,664.84
114,8905797,CLEUDSON BARREIROS GONCALVES,APPGG3,SEGES,2021-11-03,3,False,15414.90,1284.58,428.19,325.25,664.84
141,8980071,VICTOR HUGO MASSAMI RIOS MORIZONO,APPGG1,CGM,2026-04-27,1,False,13671.75,1139.31,379.77,325.25,664.84

### Contribuicao previdenciaria

Para calcular a contribuicao previdenciaria precisamos saber se a pessoa entrou antes de 2018 (ou seja, se é do IPREM) ou depois (se é do SAMPAPREV)

In [133]:
def valor_iprem(row):

    CONTRIBUICAO_IPREM = 0.28

    if not row['contribui_rpps']:
        return 0
    
    # o iprem nao considera o terço adicional de férias
    valor_base = row['vencimento'] + row['decimo_terceiro']
    
    return round(valor_base * CONTRIBUICAO_IPREM, 2)

In [134]:
appggs_atual['contribuicao_iprem'] = appggs_atual.apply(valor_iprem, axis=1)

In [135]:
appggs_atual.sample(4)

,rf,nome,cargo_base,secretaria_dez_2025,dt_inicio_exercicio,nivel_carreira,contribui_rpps,vencimento,decimo_terceiro,terco_ferias,vale_alimentacao,vale_refeicao,contribuicao_iprem
171,9412034,EDSON DE BARROS OLIVEIRA,APPGG1,SEME,2024-07-24,1,False,13671.75,1139.31,379.77,325.25,664.84,0.00
121,8915211,LUCAS DE CASTRO SENA,APPGG2,SMADS,2022-03-18,2,False,15038.93,1253.24,417.75,325.25,664.84,0.00
38,8359024,BRENDA MACHADO FONSECA,APPGG6,SEGES,2016-06-15,6,True,16600.15,1383.35,461.12,0.00,664.84,5035.38
165,9411941,MARCELO ARTHUR DE ANDRADE SANT ANA,APPGG1,SMC,2024-09-09,1,False,13671.75,1139.31,379.77,325.25,664.84,0.00

In [136]:
def contribuicao_inss(row):

    ALIQUOTA_INSS = 0.21
    TETO_INSS = 8475.55

    if row['contribui_rpps']:
        return 0
    
    # o inss vai sobre todos os vencimentos, incluso terco adicional
    valor_base = row['vencimento'] + row['terco_ferias'] + row['decimo_terceiro']

    #só para validar o teto - no caso de APPGG da na mesma porque tá todo mundo acima, mas pra deixar a funcao correta
    if valor_base > TETO_INSS:
        valor_base = TETO_INSS
        
    return round(valor_base*ALIQUOTA_INSS, 2)

In [137]:
appggs_atual['contribuicao_inss'] = appggs_atual.apply(contribuicao_inss, axis=1)

In [138]:
appggs_atual.sample(4)

,rf,nome,cargo_base,secretaria_dez_2025,dt_inicio_exercicio,nivel_carreira,contribui_rpps,vencimento,decimo_terceiro,terco_ferias,vale_alimentacao,vale_refeicao,contribuicao_iprem,contribuicao_inss
60,8359491,THIAGO FERREIRA DE SOUZA,APPGG6,SMSUB,2016-06-17,6,True,16600.15,1383.35,461.12,0.00,664.84,5035.38,0.00
68,8400164,GUILHERME GALUPPO BORBA,APPGG5,SEGES,2017-03-29,5,True,16195.27,1349.61,449.87,325.25,664.84,4912.57,0.00
80,8437904,ANDRE RICARDO MARTELINI,APPGG1,SMADS,2024-10-07,1,False,13671.75,1139.31,379.77,325.25,664.84,0.00,1779.87
11,8111618,VINICIUS PEDRON MACARIO,APPGG6,SEGES,2016-06-20,6,True,16600.15,1383.35,461.12,0.00,664.84,5035.38,0.00

In [139]:
def previdencia_complementar(row):

    TETO_INSS = 8475.55
    ALIQUOTA_COMPLEMENTAR = 0.075
    if row['contribui_rpps']:
        return 0
    
    valor_base = row['vencimento'] + row['decimo_terceiro']
    #só contribui o que é acima do teto
    valor_base = valor_base - TETO_INSS

    return round(valor_base * ALIQUOTA_COMPLEMENTAR, 2)

In [140]:
appggs_atual['previdencia_complementar'] = appggs_atual.apply(previdencia_complementar, axis=1)

In [141]:
appggs_atual.sample(4)

,rf,nome,cargo_base,secretaria_dez_2025,dt_inicio_exercicio,nivel_carreira,contribui_rpps,vencimento,decimo_terceiro,terco_ferias,vale_alimentacao,vale_refeicao,contribuicao_iprem,contribuicao_inss,previdencia_complementar
156,9411836,LAURA MENEGHEL DOS SANTOS,APPGG1,SEME,2024-08-02,1,False,13671.75,1139.31,379.77,325.25,664.84,0.0,1779.87,475.16
96,8894230,CASSIANA MONTESIAO DE SOUSA,APPGG3,SEGES,2021-09-23,3,False,15414.90,1284.58,428.19,325.25,664.84,0.0,1779.87,616.79
83,8475024,RODOLFO FREIRE MAICHE,APPGG5,SVMA,2018-01-09,5,False,16195.27,1349.61,449.87,325.25,664.84,0.0,1779.87,680.20
12,8113441,ANDRE SCHIFNAGEL AVRICHIR,APPGG1,SEGES,2022-04-20,1,False,13671.75,1139.31,379.77,325.25,664.84,0.0,1779.87,475.16

In [142]:
def calculo_ir_simples(base_calculo:float)->float:
    '''Calcula o IR de forma simplificada considerando que todos os APPGGs ganham já acima da última faixa
    então não precisa aplicar redutor nem isenção etc.'''

    ultima_faixa = 7350
    if base_calculo <= ultima_faixa:
        raise ValueError('Base de cálculo deve ser maior que a última faixa para o cálculo simplificado.')

    aliquota = 0.275
    deducao = 908.73
    return round((base_calculo*aliquota)-deducao, 2)

def irpf_recolhido_na_fonte(row):

    #o IRPF é sobre vencimento + 3o adicional de ferias + 13o, ou seja, sobre tudo que é pago mensalmente

    base_calculo = row['vencimento'] + row['terco_ferias'] + row['decimo_terceiro']
    #considerando que todos os APPGGs ganham acima da última faixa, posso usar o cálculo simplificado
    return calculo_ir_simples(base_calculo)

In [143]:
appggs_atual['irpf_na_fonte'] = appggs_atual.apply(irpf_recolhido_na_fonte, axis=1)
appggs_atual.sample(4)

,rf,nome,cargo_base,secretaria_dez_2025,dt_inicio_exercicio,nivel_carreira,contribui_rpps,vencimento,decimo_terceiro,terco_ferias,vale_alimentacao,vale_refeicao,contribuicao_iprem,contribuicao_inss,previdencia_complementar,irpf_na_fonte
71,8411671,ALISSON RODRIGUES PINHEIRO,APPGG1,SEGES,2024-07-16,1,False,13671.75,1139.31,379.77,325.25,664.84,0.00,1779.87,475.16,3268.75
5,8038848,RODRIGO RAVACCI BRISOLA,APPGG1,SMUL,2026-04-02,1,False,13671.75,1139.31,379.77,325.25,664.84,0.00,1779.87,475.16,3268.75
49,8359229,ANANDA GRINKRAUT,APPGG6,SME,2016-06-24,6,True,16600.15,1383.35,461.12,0.00,664.84,5035.38,0.00,0.00,4163.54
151,9411763,MARIANA D UGO GUIMARAES,APPGG1,SMT,2024-08-26,1,False,13671.75,1139.31,379.77,325.25,664.84,0.00,1779.87,475.16,3268.75

## Valor total

Agora calculamos o valor total e salvamos os dados

In [144]:
def valor_total_prefeitura(row):

    vencimentos = row['vencimento'] + row['decimo_terceiro'] + row['terco_ferias']
    auxilios = row['vale_alimentacao'] + row['vale_refeicao']
    previdencia = row['contribuicao_iprem'] + row['contribuicao_inss'] + row['previdencia_complementar']

    custos_totais = vencimentos + auxilios + previdencia
    #agora tem que tirar o irpf porque a prefeitura recolhe na fonte e já vai pro tesouro
    irpf = row['irpf_na_fonte']
    return round(custos_totais - irpf, 2)

In [145]:
appggs_atual['valor_total_prefeitura'] = appggs_atual.apply(valor_total_prefeitura, axis=1)

In [146]:
appggs_atual.head()

,rf,nome,cargo_base,secretaria_dez_2025,dt_inicio_exercicio,nivel_carreira,contribui_rpps,vencimento,decimo_terceiro,terco_ferias,vale_alimentacao,vale_refeicao,contribuicao_iprem,contribuicao_inss,previdencia_complementar,irpf_na_fonte,valor_total_prefeitura
0,6394604,CLAUDIO AGUIAR ALMEIDA,APPGG3,SMC,2021-10-01,3,False,15414.90,1284.58,428.19,325.25,664.84,0.00,1779.87,616.79,3801.38,16713.04
1,7575491,MAURICIO DA SILVA CORREIA,APPGG1,SEGES,2021-11-03,1,False,13671.75,1139.31,379.77,325.25,664.84,0.00,1779.87,475.16,3268.75,15167.20
2,7718543,MARCIA MIYUKI ISHIKAWA,APPGG2,SEHAB,2021-12-08,2,False,15038.93,1253.24,417.75,325.25,664.84,0.00,1779.87,586.25,3686.50,16379.63
3,7794720,TIAGO ROSA MACHADO,APPGG2,SEME,2022-01-05,2,False,15038.93,1253.24,417.75,325.25,664.84,0.00,1779.87,586.25,3686.50,16379.63
4,7840501,THAIS ROBERTO DA SILVA,APPGG5,SMDHC,2017-11-29,5,True,16195.27,1349.61,449.87,325.25,664.84,4912.57,0.00,0.00,4039.83,19857.58

In [147]:
appggs_atual.to_csv('situacao_atual.csv', sep=';')

# Proposta equiparação AMCI

Agora calculamos quais seriam as contribuicoes da Prefeitura com base na equiparação com a tabela dos AMCI

In [148]:
tabela_amci = {
    1 : 16840.38,
    2 : 17682.41,
    3 : 18036.04,
    4 : 18396.78,
    5 : 18764.71,
    6 : 19139.99,
    7 : 20097.00,
    8 : 20498.94,
    9 : 20908.92,
    10 : 21327.10,
    11 : 21753.64,
    12 : 22841.33,
    13 : 23183.95,
    14 : 23531.72,
    15 : 23884.67
}

In [149]:
tabela_amci = reajuste_maio(tabela_amci)
tabela_amci

{1: 17431.48,
 2: 18303.06,
 3: 18669.11,
 4: 19042.51,
 5: 19423.35,
 6: 19811.8,
 7: 20802.4,
 8: 21218.45,
 9: 21642.82,
 10: 22075.68,
 11: 22517.19,
 12: 23643.06,
 13: 23997.71,
 14: 24357.68,
 15: 24723.02}

In [150]:
proposta_amci = appggs.copy(deep=True)

In [151]:
proposta_amci.head()

,rf,nome,cargo_base,secretaria_dez_2025,dt_inicio_exercicio,nivel_carreira,contribui_rpps
0,6394604,CLAUDIO AGUIAR ALMEIDA,APPGG3,SMC,2021-10-01,3,False
1,7575491,MAURICIO DA SILVA CORREIA,APPGG1,SEGES,2021-11-03,1,False
2,7718543,MARCIA MIYUKI ISHIKAWA,APPGG2,SEHAB,2021-12-08,2,False
3,7794720,TIAGO ROSA MACHADO,APPGG2,SEME,2022-01-05,2,False
4,7840501,THAIS ROBERTO DA SILVA,APPGG5,SMDHC,2017-11-29,5,True

Agora vamos calcular rapidamente o que fizemos na seção anterior, qual seja:
1. o novo vencimento,
2. o décimo terceiro,
3. o terço adicional de férias,
4. o auxilio alimentacao,
5. as contribuicoes previdenciarias

In [152]:
#vencimento
proposta_amci['vencimento'] = proposta_amci['nivel_carreira'].map(tabela_amci)
#ferias e decimo terceiro
proposta_amci['decimo_terceiro'] = proposta_amci.apply(calcular_decimo_terceiro, axis=1)
proposta_amci['terco_ferias'] = proposta_amci.apply(calcular_terco_ferias, axis=1)
#vale alimentacao
proposta_amci['vale_alimentacao'] = proposta_amci.apply(calcular_va, axis=1)
proposta_amci['vale_refeicao'] = proposta_amci.apply(vale_refeicao, axis=1)
#previdencia
proposta_amci['contribuicao_iprem'] = proposta_amci.apply(valor_iprem, axis=1)
proposta_amci['contribuicao_inss'] = proposta_amci.apply(contribuicao_inss, axis=1)
proposta_amci['previdencia_complementar'] = proposta_amci.apply(previdencia_complementar, axis=1)
#irpf
proposta_amci['irpf_na_fonte'] = proposta_amci.apply(irpf_recolhido_na_fonte, axis=1)
#VALOR TOTAL PROPOSTA
proposta_amci['valor_total_prefeitura'] = proposta_amci.apply(valor_total_prefeitura, axis=1)

In [153]:
proposta_amci.head()

,rf,nome,cargo_base,secretaria_dez_2025,dt_inicio_exercicio,nivel_carreira,contribui_rpps,vencimento,decimo_terceiro,terco_ferias,vale_alimentacao,vale_refeicao,contribuicao_iprem,contribuicao_inss,previdencia_complementar,irpf_na_fonte,valor_total_prefeitura
0,6394604,CLAUDIO AGUIAR ALMEIDA,APPGG3,SMC,2021-10-01,3,False,18669.11,1555.76,518.59,0,664.84,0.00,1779.87,881.20,4795.72,19273.65
1,7575491,MAURICIO DA SILVA CORREIA,APPGG1,SEGES,2021-11-03,1,False,17431.48,1452.62,484.21,0,664.84,0.00,1779.87,780.64,4417.56,18176.10
2,7718543,MARCIA MIYUKI ISHIKAWA,APPGG2,SEHAB,2021-12-08,2,False,18303.06,1525.26,508.42,0,664.84,0.00,1779.87,851.46,4683.87,18949.04
3,7794720,TIAGO ROSA MACHADO,APPGG2,SEME,2022-01-05,2,False,18303.06,1525.26,508.42,0,664.84,0.00,1779.87,851.46,4683.87,18949.04
4,7840501,THAIS ROBERTO DA SILVA,APPGG5,SMDHC,2017-11-29,5,True,19423.35,1618.61,539.54,0,664.84,5891.75,0.00,0.00,5026.18,23111.91

In [154]:
proposta_amci.to_csv('proposta_amci.csv', sep=';')

# Proposta reajuste inflação
### Reajuste tabela original

In [155]:
tabela_original = {
    1 : 9000.00,
    2 : 10080.00,
    3 : 10684.80,
    4 : 11325.89,
    5 : 12005.44,
    6 : 12725.77,
    7 : 13998.34,
    8 : 14698.26,
    9 : 15433.17,
    10 : 16204.83,
    11 : 17015.08,
    12 : 18716.58,
    13 : 19558.83,
    14 : 20438.98,
    15 : 21358.73
}

In [156]:
calculadora_inflacao = CalculadoraFatorInflacao('ipc-fipe')

In [157]:
# nesse momento o ultimo valor do IPCA disponível é para junho de 2026
fator_ipc = calculadora_inflacao('01/06/2016', '01/07/2026')

Dados obtidos com sucesso na URL: https://api.bcb.gov.br/dados/serie/bcdata.sgs.193/dados?formato=json&dataInicial=01%2F06%2F2016&dataFinal=01%2F07%2F2026

In [158]:
fator_ipc

1.5993434131152044

In [159]:
#Só vendo para efeitos de comparacao
fator_ipca = CalculadoraFatorInflacao('ipca')('01/06/2016', '01/03/2026')
fator_ipca

Dados obtidos com sucesso na URL: https://api.bcb.gov.br/dados/serie/bcdata.sgs.433/dados?formato=json&dataInicial=01%2F06%2F2016&dataFinal=01%2F03%2F2026

1.613929066220535

In [160]:
tabela_atualizada = {nivel : round(valor*fator_ipc, 2) for nivel, valor in tabela_original.items()}
tabela_atualizada

{1: 14394.09,
 2: 16121.38,
 3: 17088.66,
 4: 18113.99,
 5: 19200.82,
 6: 20352.88,
 7: 22388.15,
 8: 23507.57,
 9: 24682.94,
 10: 25917.09,
 11: 27212.96,
 12: 29934.24,
 13: 31281.29,
 14: 32688.95,
 15: 34159.94}

In [161]:
if tabela_atualizada[1] > tabela_atual[1]:
    print('O reajuste pelo IPC é maior do que o reajuste concedido atualmente pela prefeitura, portanto podemos manter os valores, caso contrario se algum nível no reajuste atual fosse maior, teria que manter esse nível e não o da tabela atualizada pois não pode reduzir salário.')

O reajuste pelo IPC é maior do que o reajuste concedido atualmente pela prefeitura, portanto podemos manter os valores, caso contrario se algum nível no reajuste atual fosse maior, teria que manter esse nível e não o da tabela atualizada pois não pode reduzir salário.

In [162]:
proposta_ipc = appggs.copy(deep=True)

In [163]:
#vencimento
proposta_ipc['vencimento'] = proposta_ipc['nivel_carreira'].map(tabela_atualizada)
#ferias e decimo terceiro
proposta_ipc['decimo_terceiro'] = proposta_ipc.apply(calcular_decimo_terceiro, axis=1)
proposta_ipc['terco_ferias'] = proposta_ipc.apply(calcular_terco_ferias, axis=1)
#vale alimentacao
proposta_ipc['vale_alimentacao'] = proposta_ipc.apply(calcular_va, axis=1)
proposta_ipc['vale_refeicao'] = proposta_ipc.apply(vale_refeicao, axis=1)
#previdencia
proposta_ipc['contribuicao_iprem'] = proposta_ipc.apply(valor_iprem, axis=1)
proposta_ipc['contribuicao_inss'] = proposta_ipc.apply(contribuicao_inss, axis=1)
proposta_ipc['previdencia_complementar'] = proposta_ipc.apply(previdencia_complementar, axis=1)
#irpf
proposta_ipc['irpf_na_fonte'] = proposta_ipc.apply(irpf_recolhido_na_fonte, axis=1)
#VALOR TOTAL PROPOSTA
proposta_ipc['valor_total_prefeitura'] = proposta_ipc.apply(valor_total_prefeitura, axis=1)

In [164]:
proposta_ipc.head()

,rf,nome,cargo_base,secretaria_dez_2025,dt_inicio_exercicio,nivel_carreira,contribui_rpps,vencimento,decimo_terceiro,terco_ferias,vale_alimentacao,vale_refeicao,contribuicao_iprem,contribuicao_inss,previdencia_complementar,irpf_na_fonte,valor_total_prefeitura
0,6394604,CLAUDIO AGUIAR ALMEIDA,APPGG3,SMC,2021-10-01,3,False,17088.66,1424.06,474.69,0.00,664.84,0.00,1779.87,752.79,4312.81,17872.10
1,7575491,MAURICIO DA SILVA CORREIA,APPGG1,SEGES,2021-11-03,1,False,14394.09,1199.51,399.84,325.25,664.84,0.00,1779.87,533.85,3489.47,15807.78
2,7718543,MARCIA MIYUKI ISHIKAWA,APPGG2,SEHAB,2021-12-08,2,False,16121.38,1343.45,447.82,325.25,664.84,0.00,1779.87,674.20,4017.25,17339.56
3,7794720,TIAGO ROSA MACHADO,APPGG2,SEME,2022-01-05,2,False,16121.38,1343.45,447.82,325.25,664.84,0.00,1779.87,674.20,4017.25,17339.56
4,7840501,THAIS ROBERTO DA SILVA,APPGG5,SMDHC,2017-11-29,5,True,19200.82,1600.07,533.36,0.00,664.84,5824.25,0.00,0.00,4958.19,22865.15

In [165]:
proposta_ipc.to_csv('proposta_ipc.csv', sep=';')

### Reajuste tabela Gestão Nunes

In [166]:
# agora consideramos junho de 2021 como o ano base
# vamos usar a tabela original como base porque só teve reajuste de 0.001% nesse período então nem compensa atualizar

In [167]:
fator_ipc_nunes = calculadora_inflacao('01/06/2021', '01/03/2026')

Dados obtidos com sucesso na URL: https://api.bcb.gov.br/dados/serie/bcdata.sgs.193/dados?formato=json&dataInicial=01%2F06%2F2021&dataFinal=01%2F03%2F2026

In [168]:
fator_ipc_nunes

1.2996596073748405

In [169]:
tabela_atualizada_nunes = {nivel : round(valor*fator_ipc_nunes, 2) for nivel, valor in tabela_original.items()}
tabela_atualizada_nunes

{1: 11696.94,
 2: 13100.57,
 3: 13886.6,
 4: 14719.8,
 5: 15602.99,
 6: 16539.17,
 7: 18193.08,
 8: 19102.73,
 9: 20057.87,
 10: 21060.76,
 11: 22113.81,
 12: 24325.18,
 13: 25419.82,
 14: 26563.72,
 15: 27759.08}

Só a comparação com a tabela atual permite identificar que alguns níveis já tiveram reajuste até acima da inflação da gestão. Então no caso vamos manter esses niveis como estão.

In [170]:
tabela_atual

{1: 13671.75,
 2: 15038.93,
 3: 15414.9,
 4: 15800.26,
 5: 16195.27,
 6: 16600.15,
 7: 18592.19,
 8: 19056.99,
 9: 19533.41,
 10: 20021.73,
 11: 20522.3,
 12: 22637.37,
 13: 23203.29,
 14: 23783.38,
 15: 24377.96}

In [171]:
tabela_atualizada_nunes = {nivel : valor if valor>tabela_atual[nivel] else tabela_atual[nivel]
                           for nivel, valor in tabela_atualizada_nunes.items()}

In [172]:
tabela_atualizada_nunes

{1: 13671.75,
 2: 15038.93,
 3: 15414.9,
 4: 15800.26,
 5: 16195.27,
 6: 16600.15,
 7: 18592.19,
 8: 19102.73,
 9: 20057.87,
 10: 21060.76,
 11: 22113.81,
 12: 24325.18,
 13: 25419.82,
 14: 26563.72,
 15: 27759.08}

In [173]:
proposta_ipc_nunes = appggs.copy(deep=True)

In [174]:
#vencimento
proposta_ipc_nunes['vencimento'] = proposta_ipc_nunes['nivel_carreira'].map(tabela_atualizada_nunes)
#ferias e decimo terceiro
proposta_ipc_nunes['decimo_terceiro'] = proposta_ipc_nunes.apply(calcular_decimo_terceiro, axis=1)
proposta_ipc_nunes['terco_ferias'] = proposta_ipc_nunes.apply(calcular_terco_ferias, axis=1)
#vale alimentacao
proposta_ipc_nunes['vale_alimentacao'] = proposta_ipc_nunes.apply(calcular_va, axis=1)
proposta_ipc_nunes['vale_refeicao'] = proposta_ipc_nunes.apply(vale_refeicao, axis=1)
#previdencia
proposta_ipc_nunes['contribuicao_iprem'] = proposta_ipc_nunes.apply(valor_iprem, axis=1)
proposta_ipc_nunes['contribuicao_inss'] = proposta_ipc_nunes.apply(contribuicao_inss, axis=1)
proposta_ipc_nunes['previdencia_complementar'] = proposta_ipc_nunes.apply(previdencia_complementar, axis=1)
#irpf
proposta_ipc_nunes['irpf_na_fonte'] = proposta_ipc_nunes.apply(irpf_recolhido_na_fonte, axis=1)
#VALOR TOTAL PROPOSTA
proposta_ipc_nunes['valor_total_prefeitura'] = proposta_ipc_nunes.apply(valor_total_prefeitura, axis=1)

In [175]:
proposta_ipc_nunes.head()

,rf,nome,cargo_base,secretaria_dez_2025,dt_inicio_exercicio,nivel_carreira,contribui_rpps,vencimento,decimo_terceiro,terco_ferias,vale_alimentacao,vale_refeicao,contribuicao_iprem,contribuicao_inss,previdencia_complementar,irpf_na_fonte,valor_total_prefeitura
0,6394604,CLAUDIO AGUIAR ALMEIDA,APPGG3,SMC,2021-10-01,3,False,15414.90,1284.58,428.19,325.25,664.84,0.00,1779.87,616.79,3801.38,16713.04
1,7575491,MAURICIO DA SILVA CORREIA,APPGG1,SEGES,2021-11-03,1,False,13671.75,1139.31,379.77,325.25,664.84,0.00,1779.87,475.16,3268.75,15167.20
2,7718543,MARCIA MIYUKI ISHIKAWA,APPGG2,SEHAB,2021-12-08,2,False,15038.93,1253.24,417.75,325.25,664.84,0.00,1779.87,586.25,3686.50,16379.63
3,7794720,TIAGO ROSA MACHADO,APPGG2,SEME,2022-01-05,2,False,15038.93,1253.24,417.75,325.25,664.84,0.00,1779.87,586.25,3686.50,16379.63
4,7840501,THAIS ROBERTO DA SILVA,APPGG5,SMDHC,2017-11-29,5,True,16195.27,1349.61,449.87,325.25,664.84,4912.57,0.00,0.00,4039.83,19857.58

In [176]:
proposta_ipc_nunes.to_csv('proposta_ipc_nunes.csv', sep=';')

In [177]:
def tabela_to_pandas(tabela:dict, tabela_name:str):

    dados = []
    for nivel, val in tabela.items():
        dados.append([tabela_name, nivel, val])

    return pd.DataFrame(dados, columns = ['nome_tabela', 'nivel', 'vencimento'])

In [178]:
tabelas = {
    'atual' : tabela_atual,
    'original' : tabela_original,
    'amci' : tabela_amci,
    'original_atualizada_ipc' : tabela_atualizada,
    'original_atualizada_ipc_nunes' : tabela_atualizada_nunes

}

In [179]:
dfs_tabelas = [tabela_to_pandas(tabela, tabela_name) for tabela_name, tabela in tabelas.items()]
df_tabelas = pd.concat(dfs_tabelas)

df_tabelas

                      nome_tabela  nivel  vencimento
0                           atual      1    13671.75
1                           atual      2    15038.93
2                           atual      3    15414.90
3                           atual      4    15800.26
4                           atual      5    16195.27
..                            ...    ...         ...
10  original_atualizada_ipc_nunes     11    22113.81
11  original_atualizada_ipc_nunes     12    24325.18
12  original_atualizada_ipc_nunes     13    25419.82
13  original_atualizada_ipc_nunes     14    26563.72
14  original_atualizada_ipc_nunes     15    27759.08

[75 rows x 3 columns]

In [180]:
df_tabelas.to_csv('tabelas_vencimentos_utilizadas.csv', sep=';')

# Agregações

Agora fazemos as agregações para analisar o impacto orçamentário

In [181]:
def total_mensal_por_nivel(servidores, nome_proposta:str):

    df = servidores.groupby('nivel_carreira')['valor_total_prefeitura'].sum().reset_index()
    df['id_proposta'] = nome_proposta
    return df

In [182]:
total_atual = total_mensal_por_nivel(appggs_atual, 'situacao_atual')
total_atual

   nivel_carreira  valor_total_prefeitura     id_proposta
0               1              1184933.67  situacao_atual
1               2               589666.68  situacao_atual
2               3               436818.23  situacao_atual
3               4                19419.56  situacao_atual
4               5               295411.20  situacao_atual
5               6               759289.40  situacao_atual

In [183]:
total_amci = total_mensal_por_nivel(proposta_amci, 'unificacao_amci')
total_amci

   nivel_carreira  valor_total_prefeitura      id_proposta
0               1              1420462.84  unificacao_amci
1               2               682165.44  unificacao_amci
2               3               504116.79  unificacao_amci
3               4                22689.60  unificacao_amci
4               5               343509.25  unificacao_amci
5               6               894620.70  unificacao_amci

In [184]:
total_ipc = total_mensal_por_nivel(proposta_ipc, 'reajuste_ipc')
total_ipc

   nivel_carreira  valor_total_prefeitura   id_proposta
0               1              1235059.33  reajuste_ipc
1               2               624224.16  reajuste_ipc
2               3               467325.50  reajuste_ipc
3               4                21659.98  reajuste_ipc
4               5               339857.27  reajuste_ipc
5               6               917420.70  reajuste_ipc

In [185]:
total_ipc_nunes = total_mensal_por_nivel(proposta_ipc_nunes, 'reajuste_ipc_gestao_nunes')
total_ipc_nunes

   nivel_carreira  valor_total_prefeitura                id_proposta
0               1              1184933.67  reajuste_ipc_gestao_nunes
1               2               589666.68  reajuste_ipc_gestao_nunes
2               3               436818.23  reajuste_ipc_gestao_nunes
3               4                19419.56  reajuste_ipc_gestao_nunes
4               5               295411.20  reajuste_ipc_gestao_nunes
5               6               759289.40  reajuste_ipc_gestao_nunes

In [186]:
def impacto_mensal(situacao_atual, proposta):

    join = pd.merge(situacao_atual, proposta, on='nivel_carreira', suffixes=('_atual', '_proposta'))
    join['impacto_mensal'] = join['valor_total_prefeitura_proposta'] - join['valor_total_prefeitura_atual']

    return join

In [187]:
impacto_mensal_amci = impacto_mensal(total_atual, total_amci)
impacto_mensal_ipca = impacto_mensal(total_atual, total_ipc)
impacto_mensal_ipca_nunes = impacto_mensal(total_atual, total_ipc_nunes)

In [188]:
impacto_mensal_amci.to_csv('impacto_mensal_amci.csv', sep=';')
impacto_mensal_amci

,nivel_carreira,valor_total_prefeitura_atual,id_proposta_atual,valor_total_prefeitura_proposta,id_proposta_proposta,impacto_mensal
0,1,1184933.67,situacao_atual,1420462.84,unificacao_amci,235529.17
1,2,589666.68,situacao_atual,682165.44,unificacao_amci,92498.76
2,3,436818.23,situacao_atual,504116.79,unificacao_amci,67298.56
3,4,19419.56,situacao_atual,22689.60,unificacao_amci,3270.04
4,5,295411.20,situacao_atual,343509.25,unificacao_amci,48098.05
5,6,759289.40,situacao_atual,894620.70,unificacao_amci,135331.30

In [189]:
impacto_mensal_ipca.to_csv('impacto_mensal_ipc.csv', sep=';')
impacto_mensal_ipca

,nivel_carreira,valor_total_prefeitura_atual,id_proposta_atual,valor_total_prefeitura_proposta,id_proposta_proposta,impacto_mensal
0,1,1184933.67,situacao_atual,1235059.33,reajuste_ipc,50125.66
1,2,589666.68,situacao_atual,624224.16,reajuste_ipc,34557.48
2,3,436818.23,situacao_atual,467325.50,reajuste_ipc,30507.27
3,4,19419.56,situacao_atual,21659.98,reajuste_ipc,2240.42
4,5,295411.20,situacao_atual,339857.27,reajuste_ipc,44446.07
5,6,759289.40,situacao_atual,917420.70,reajuste_ipc,158131.30

In [190]:
impacto_mensal_ipca_nunes.to_csv('impacto_mensal_ipc_nunes.csv', sep=';')
impacto_mensal_ipca_nunes

,nivel_carreira,valor_total_prefeitura_atual,id_proposta_atual,valor_total_prefeitura_proposta,id_proposta_proposta,impacto_mensal
0,1,1184933.67,situacao_atual,1184933.67,reajuste_ipc_gestao_nunes,0.0
1,2,589666.68,situacao_atual,589666.68,reajuste_ipc_gestao_nunes,0.0
2,3,436818.23,situacao_atual,436818.23,reajuste_ipc_gestao_nunes,0.0
3,4,19419.56,situacao_atual,19419.56,reajuste_ipc_gestao_nunes,0.0
4,5,295411.20,situacao_atual,295411.20,reajuste_ipc_gestao_nunes,0.0
5,6,759289.40,situacao_atual,759289.40,reajuste_ipc_gestao_nunes,0.0

In [191]:
impactos_anuais = {
'reajuste_ipc_gestao_nunes' : round(impacto_mensal_ipca_nunes['impacto_mensal'].sum()*12, 2),
'reajuste_ipc' : round(impacto_mensal_ipca['impacto_mensal'].sum()*12, 2),
'reajuste_amci' : round(impacto_mensal_amci['impacto_mensal'].sum()*12, 2),
}

In [192]:
tabela_to_pandas(impactos_anuais, 'impactos_anuais').drop('nome_tabela', axis=1).to_csv('impactos_anuais.csv', sep=';')